/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import DAO.InitConnexion;
import DAO.PompierDAO;
import java.sql.Connection;
import modeles.Professionnel;

/**
 *
 * @author noa.hervieu
 */
public class frm_pompier extends javax.swing.JFrame {

    /**
     * Creates new form frm_pompier
     */
    public frm_pompier() {
        
        initComponents();
        Connection connection = InitConnexion.ouvrirConnexion();
        
        Professionnel professionnelByMatricule = PompierDAO.getProfessionnelByMatricule(connection, 3);
        
        String prenom = professionnelByMatricule.getPrenom();
        String nom = professionnelByMatricule.getNom();
        
        lab_bonjour.setText("Bonjour, " + prenom);
        
        Txt_prenom.setText(prenom);
        Txt_nom.setText(nom);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_bonjour = new javax.swing.JLabel();
        Txt_prenom = new javax.swing.JTextField();
        Lab_Prenom = new javax.swing.JLabel();
        Txt_nom = new javax.swing.JTextField();
        Lab_nom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lab_bonjour.setText("jLabel1");

        Txt_prenom.setText("jTextField1");
        Txt_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_prenomActionPerformed(evt);
            }
        });

        Lab_Prenom.setText("Prénom : ");

        Txt_nom.setText("jTextField1");
        Txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_nomActionPerformed(evt);
            }
        });

        Lab_nom.setText("Nom : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lab_bonjour))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lab_nom)
                                .addGap(33, 33, 33)
                                .addComponent(Txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lab_Prenom)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_bonjour)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lab_Prenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lab_nom))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_prenomActionPerformed

    private void Txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_pompier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_pompier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_pompier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_pompier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_pompier().setVisible(true);
            }
        });
        
       

       // System.out.println("Nom : " + professionnelByMatricule.getNom());
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lab_Prenom;
    private javax.swing.JLabel Lab_nom;
    private javax.swing.JTextField Txt_nom;
    private javax.swing.JTextField Txt_prenom;
    private javax.swing.JLabel lab_bonjour;
    // End of variables declaration//GEN-END:variables

}
