/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;
import DAO.PompierDAO;
import java.sql.Connection;
/**
 *
 * @author louane.roussel
 */
public class frm_inscriptionV extends javax.swing.JFrame {

    /**
     * Creates new form frm_inscription
     */
    String vNom;
    String vPrenom;
    String vDateNaissance;
    String vNumeroBip;
    
    public frm_inscriptionV() {
        initComponents();
    }
    
    public frm_inscriptionV(String vNom, String vPrenom, String vDateNaissance, String vNumeroBip) {
        initComponents();
        
       this.vNom = vNom;
       this.vPrenom = vPrenom ;
       this.vDateNaissance = vDateNaissance ;
       this.vNumeroBip = vNumeroBip ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inscription = new javax.swing.JLabel();
        EnAtivite = new javax.swing.JCheckBox();
        suivant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inscription.setText("inscription");

        EnAtivite.setText("en Activité");
        EnAtivite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnAtiviteActionPerformed(evt);
            }
        });

        suivant.setText("suivant");
        suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suivantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(suivant))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(EnAtivite, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(inscription)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(inscription)
                .addGap(50, 50, 50)
                .addComponent(EnAtivite)
                .addGap(18, 18, 18)
                .addComponent(suivant)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnAtiviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnAtiviteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnAtiviteActionPerformed

    private void suivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suivantActionPerformed
        // TODO add your handling code here:
        Connection connection = DAO.InitConnexion.ouvrirConnexion(); 
        
        if (EnAtivite.isSelected()){
            boolean vEnAtivite = true ;
            setVisible(false);
            frm_inscriptionV2 frm_inscriptionV2 = new frm_inscriptionV2();
            frm_inscriptionV2.setVisible(true);
         }else{
           boolean vEnAtivite = false ;
           PompierDAO.inscriptionVolontaireBdd(connection, vNom, vPrenom, vDateNaissance, vNumeroBip, vEnAtivite);
         }
    }//GEN-LAST:event_suivantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_inscriptionV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_inscriptionV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_inscriptionV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_inscriptionV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_inscriptionV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox EnAtivite;
    private javax.swing.JLabel inscription;
    private javax.swing.JButton suivant;
    // End of variables declaration//GEN-END:variables
}
